name: qgrid-environment+with_other_favs
channels:
  - tim_shawver
  - conda-forge
dependencies:
  - qgrid=1.0.0
  - pandas-datareader>=0.5.0
  - matplotlib>=2.1.1
  - seaborn
  - statsmodels
  - scipy
  - intermine
  - pip
  - pip:
    - vpnotebook
    - vpython
    - matplotlib_venn
    - openpyxl
